name: CI/CD Pipeline

on: 
  push:
    branches:
      - main  # תוכל להגדיר את ה-branch שבו זה יקרה, למשל main

jobs:
  CICD:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Dependencies for UsersService
        working-directory: ./UsersService
        run: npm install
      - name: Install Dependencies for GatewayService
        working-directory: ./GatewayService
        run: npm install
      - name: Start GatewayService and UsersService
        working-directory: ./UsersService/src
        run: node index.js &
      - name: Run Service Tests
        working-directory: ./UsersService
        run: npm test
        continue-on-error: false 
      - name: Run Linter
        run: npm run lint
        continue-on-error: false 
